apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:YQL+YA==,iv:oYgUj6K8t3HEtdwCYhElC+VYfbeaOKpOHCKTdO64luE=,tag:8C/TlwT50T8CKuwcCcwCFQ==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:OwSkSM8UVxSBfgQ=,iv:gVtx2Lots+R3h98x/o/D2oKEgyplwV7Ch5w1knzlsGo=,tag:ICPOGsChxvwd4uau5IiskA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:Bw2CPOUP2j0=,iv:pmTRGdpUyg3TyoTG9rmvBqOmGqxeaQvaBhXTuvzjHSE=,tag:/eJnLPRand6/sXta5W87CQ==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:C1Pjdq/PUH2+zN9oeWaNUZIBCIFYI7DIFmPjB8owB02gJTSH8ivlB0UASfxVp8uyQ0CFoks=,iv:URwSgY/l7+kWDUYqdeX9R2WSx18b5kEvN7xY8icfC+4=,tag:th9Xp+HpEhtEfD6bRAjOiQ==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:geBO9Joy85k=,iv:5zjFMx/TGFoEgXg7m/XHc/7Qp2L8n4dyGGUJX2eYMGM=,tag:Hw5tOeknh6v8luaFCiajhg==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:Zb8cgNgd/zQ=,iv:I9vXNV9UEIdslUsd/jO9WEuXOT7NIMw92GkUAhTEkw8=,tag:zydpzlxfGADT3ma86iJsKQ==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:KJaiYlMTHH0=,iv:gxUObuGb4p+ul4HcQa0LmrJnm9OksNN81j3wUw7aA8I=,tag:XPVRTipAoMQSlyDAm6dsKQ==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ENC[AES256_GCM,data:9mLNOuiRYwg=,iv:YLrmYwWUJfrGeW0VNmVGGf6uVefDjdlssjCqyO5N7UQ=,tag:Rm28uPKf+3k/7CYMn6QGrw==,type:str]
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:6SsbxMOgMw11Ww==,iv:9EYEFeQqx5j4HY6b7xSa8/YdlIqIF79U95sptcbffVg=,tag:BZCMiHRToN4qd+phgmoh/g==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:tYdKwsBXh1fM,iv:jDLCUdKIVjQVid6duC2uFgztpSRMJPQoBMdhE86E1Sg=,tag:AHSMuaom1CcHu35UAZYrew==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:B4/G8EkmJox8ek9beTRJPdzkFA==,iv:s5DNiVYhtNJC+NoAYyE5Q8mzBLamLTC1yZXcxLZOuDY=,tag:F2NfRqkPW7LarPuhId2qLw==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:V7rCPUA4X8vS6x+Jihsb,iv:0XQz0oqTnAVBug0p1RJcGdH0JRkkweC+vC5qcUpizCM=,tag:00gzXTuT4R+2pmN3i8HlEw==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:yFmMimfSTO7alu1/T3mr,iv:Xmw04YhP5vmCUW7wIn5pZ7X50/cHXI1eBdntsqF8Z6Y=,tag:Y0LpGfq5ohBvfjnVpo8LEg==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:7SVTL80HW+VuXhb2tAvBv+53D4419yCGKRwNDwGFYs4LosKa,iv:N2YKiJCU0UUe3QhLETe+5GPUSi+qaHfn12rRcEddMmw=,tag:3rUEiQ05GmNfJkg4J6Bfaw==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:4zobjkEVxEh0Ufp/DMxrDbGCuXoIOqZvSf5Q52S7rjL1ty/f/idKfLy73oUIZZ/PKkhq7vV6FYPP6ffZfeZ9mcexF62tFWuqta747Mhv+c6BT8jjw2tdRlblHCgCWBQBZqsCLmVKoIKNzhBHR9rv7CCZrKmmmjBJGeCJmzlHoUuC1oU5gstr3vWVicYR1TJ8lwjiaA/2LUhcSOaSvx57EGIOLU2I43lxZ/kNv4yKQjbF21BGWMmremWzDW0Nct7idWdajIEHGvTOhUKdJ3HdGigmr826ETSY26fSZQWxXQoMcUC6k8uzh2PMdNa+6P8vVHwzwV4NvaU=,iv:Bvkf0ocffKFBLHZ7t1T8TDFOmXA3cwZ8QIR91cK5fOw=,tag:P5ukaKPf5fRme00bLId50Q==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:X1XKMK6KVrPgY3M9sNUrB5ntFlNJBcsJeYxD4LAFOhyXyrzC,iv:Mb5UmWs6Wqntocq3lFQAwSXHUAZLEVbHIfmUAo2tL7w=,tag:4JtOdVh/3pkRyaEWuSkrAw==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:IiValaT1sI1ZEurr2NoH8AlTFHLUhgjC9bcEnfG+JPH4KyVXvm+oPTE2ITvfny9J8kereoqIIJ5yuLcX0aBuiA==,iv:r9yDyM2EDMKokA/B/jiieoSVIdxzvU6IKEiNGutYbas=,tag:31CcVS5oFfeb6ZjvWX54Ew==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Xy94QSI+Yu/aXnA=,iv:j4XHcdJXhkxX+AeNun11OMJL73mwinNxxmEyYBDT5Io=,tag:kXsKuKVhN/slcuakNmiIdw==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:ND8UX6GgqHLpP53MBHbc4iuuT/znVYcbXUNf5SOk6Mw=,iv:CPwsQDRPIGDJO8K7PsyB+EYCOkPHYtrFOp4Ap8XgLW8=,tag:5QdjE1btNkgk1gf8aJ97Yg==,type:str]
  TRELLO_API_TOKEN: ENC[AES256_GCM,data:+jRMP5vC+Js838aI+Ba7KbjuBHgEgyiRgI7SMpmM8M5Gr9dOBRmECDQicz869SETAytFIQb4UHU/rhU15kCTzSPWl0/l5dH/wG5w0A==,iv:bkO+dprSw8/L2JO2wEHyxZKFoLYCukZT6T4FJXteSks=,tag:RQXzGmt5dkVdT9Zcj5sVxQ==,type:str]
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:8HLGFRwojZ6Ynt+bSBWxsdg0QfaZnZiwlG+6KKuYgohsLSH8NhlEtG/irg+mVcXsGE9oUfhjp/CsKncMrWMoMh/4A+QYwjDBtnnc6ePMRYITNIR4Kl0TRg83NgezE93UXUwltYylxG4r0NK3uZXR82oM8N/STYDxllM3K6SqGo841rifJDAiRVNZRixSvYd6LNtAaeRpiQYRs4Xo4MokII9SlgqT0F2tO7lnaA==,iv:rSO1Fsm8s05C0AUh2wIu/3AxxLuD3ZWTu8/+ukL+tho=,tag:MVj3uZIJlJFIxmvAcSZvpg==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:4JBFFLZXmQjq7RUEj2sJxgHxUReqELp9eJDqkFfth3M=,iv:GVgXjFNA8WDMfT3I+EuVM7DZbDb+CjYiDeKSaa1uNEw=,tag:zje/34RhRv/ncYeI/D+44g==,type:str]
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:N/sWHHjDeV2BXap1y/L/4oeVNyfMz85SvFowGJRJf0Md8XbzR2+fLly5Er1QpTzaalVHb0+YmDOaFVcmVpBIP5mQkR+8C5ltpiYijTokmdZ+jZT3w9dinI97o/VTYFg4CBzQo9DAtRv8ayBT,iv:2VL2FoN/vlr9wW9NMCxpowlVtqLX9pkMWCPw8DEdXxE=,tag:MHymq4jEDGxFswZY5bz5Zg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:1vXrLWf/YchcGcmDiIzudVVVRzZxrkZ3w4HbQqi/CUN0nEhW6w707C30k/rNdInwsRjbZrtTYF4=,iv:aOEW+VgNjWPuXRdnCEvfiBLyMpQHy5EjiidD/gQBi4k=,tag:Ph/oRuzPQ0v4wdochC7zOA==,type:str]
  SYNOPHOTO_AUTH0_DOMAIN: ENC[AES256_GCM,data:Ceo/zfs90nJqqMVjXYuye0f2IuEYdhIX7DPwYun10V7K,iv:CAtW7uOHAgzu1QICb9sXNay9ipcBtCumTLRiCuANjcg=,tag:yKqspVl9xQvceuA8gvZ2Fg==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:fcMxfUuc+SGQyMUfQzISCkzaxEbxnpW2nyWgiNRyWzg=,iv:y2qWut7uHmMfAJHRv99sJIggBityHar1tuDwfFaFhB4=,tag:ENg2I3ivKWA+dmeIDusPyg==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:0RgIqTSvAO6KhwtFCIQGbadYiLtPjZF+O7FzwLfIc9iuPwKnISuLDA2TYoB8v7WAL+sEx++kLCtuqZl+EeIDbg==,iv:YnN5Udc5Vh18/bEwu5ONouDIIqHeX9Lohu2mXsu4y9I=,tag:HwXiBhY9EdmHuU04oOxabw==,type:str]
  SYNOPHOTO_ALLOWED_EMAILS: ENC[AES256_GCM,data:b6Q56I2EuhhfA5sLrd5gklzaEayQzyHXOgGWWSMx1l0aAWpHi9wKiTVWrnk6alzSoj3INWMF+g==,iv:S7BjJZR7bKDi6FgwDVAI3PNVCM1/+CUB+U1nDWnjICU=,tag:kZukZupScPz8qUYmNCZjcg==,type:str]
  SYNOPHOTO_FLASK_SECRET_KEY: ENC[AES256_GCM,data:Z9xgmvS3SzQLPUPnJU1KEZQg6t7p5We2456GhAjkrjy5dZmGHk2t2CYP5V0ALYK7M9xH1OMEgZinGczxHEfqKg==,iv:JoYhVXca/29hQsIte/wRv3gVczQwgDdoeTPPAh6RF9g=,tag:v+dgZbvYVxDUc1uTfiiQIg==,type:str]
  SYNOPHOTO_NAS_USERNAME: ENC[AES256_GCM,data:s7FHpgvxaA==,iv:bVdJL7mtUvfhNpZSwuz2AnBwflVSFGYkoeA3TvoJvPk=,tag:6W03JXthEVMviWzhoJu1YA==,type:str]
  SYNOPHOTO_NAS_PASSWORD: ENC[AES256_GCM,data:gzpvsHAq,iv:SFeBpJt0T/o4XLIDx/OzIKQk8Slebc6LZQ9qIeQq3J4=,tag:eF773P/bXKhb9QisiK/04w==,type:str]
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ENC[AES256_GCM,data:4xU/x7oezqs=,iv:Frvtre+gSEpm75XaoIfCkgC6kF1ipRl+SJSNJyCjWzM=,tag:DkFvgkb4GIFARo86ntxwWg==,type:str]
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ENC[AES256_GCM,data:D9hVzWmsxKaUvVlGbvXA1Q2BrZZ7Gjt4Mpo2tV4+U5HDcyUbWUXAFSznDhSWUTlgmBbxqr/UH/9fT4TcQR1psgT15pGUlA2N8h9Vqs6RUZ3dm35+qXjgX5OJzE5jw6aikfO89FTMh5o+ZFCuAgIc15dIWojVwkGaExXRklD4hWAeofv9EANkdp163e2+wjyMeDtuLh9jShLH7gu26+hVhkrsxZ45t/neQLbhWIpVdHKCBlEIGZgWQA==,iv:DaSfUqT/fWOsobRfiDL9Df9zS1hYaLr6BEOG4o9wMnI=,tag:ZPR7Ti4Uh21QrvEFTXnvgw==,type:str]
sops:
  age:
    - recipient: age1p2v4ph8cc072haxe2m6f2mlk3st6c4vrmqjy0saa32uu9rjqkgpqdpe6yf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreTJpQ2hWMEMvUXgxM1Jx
        ZC80NVBpbDR0eTBTL05PQlduUm5CV01hRW5nCkFkU0gwOGx6L2Q1VFIrSHZyeS9i
        R1hCakkxSmRUbnR2NGZlVk9SNU5kejAKLS0tIFJsRENtdjVZL3ZaYkoxTXBOVlpv
        RHZ0QkxIamFRVnNHVDVpY0FEeFZuczgKIjQ4houtJn5/qsMulEk8+CmgEPKy9BBm
        SLbAVZk2AV8I4qcXwheQG3lVviUF4HL9gWsJk/iQDth2VTtGJaaLLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T22:45:54Z"
  mac: ENC[AES256_GCM,data:yJD3GUOUp434dY4d9nk/by1V8A5CQiVhqhlPNS86YMY4988sOdMuBVpBDHVPwKVZOJPBKkO9kakwhWTRblZqbuWlXSWTGhhcm7r3UNUnmCSjFmv9GhiYx6d7u2U15aSMNnaR+YWq2gpNWJT6UMRV5yMw474vknSJqhcPtta4ff0=,iv:rdALejtxMPBVCxymkx4azdlUf8aTVlS6wKY89QsVsMw=,tag:osiW/8WyOZGhxXp4rZO3ag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
