apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:Tkl1NQ==,iv:9XNXj6C/jyEolKeCBGsoebpTFOBlfuoms6QPDX5rO4g=,tag:L5Rz9+fmHm04rZNVydcVWQ==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:0vPMXEswj6QKEOc=,iv:5aR1lQ1NumFnNdnplM2aEYJkoPzS9uG7RsBbquRcpvU=,tag:FM039IAqaPHmPMi5lFLWfA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:Lj1hNMmOh0s=,iv:K5pRIa4osK6UDMfn1XoJ7xIlVqN46J+f56Y11bZPrM8=,tag:5CSLB0EuRRKevNZrpxR5Og==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:IVOOEFQS4H3sJVpqOz0Lnq0ZEaf58ggaNh7WtqrscDKznbjeQkhNIT6e5918f0s5dcy+WJc=,iv:vHGE4oMqi22uvrsAiiNUFyVAdPpb83nRA8PhEsRTj28=,tag:Z4DtUJfDKkzyc0wWiX/Tgw==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:N9eZ+r6ig/4=,iv:5EWfAHXHIlBA5tb4m1NvSw+GEL9WAwboTToFe3Um8g8=,tag:MNxatrTgmCrfSS+IN9lRWQ==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:QIYS7m5PuMM=,iv:YCXx89yp3qzXiPA87a2F34GVg+H9EFAUqHwvyAqOC+E=,tag:fPANiz/SblNA1Kw6M20HiQ==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:QOop7R4G540=,iv:ne1um9xYiC6fIjR5kfemYZ9+jASt2aHTcmhAPivmHik=,tag:6cQVfVciNISWxuEgRwQMIA==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:GTxuFS/DojtX,iv:fonIyvBp9OlKFRUE+MZS511WHFgTPeIXNWbuUDcC2Jg=,tag:8TIpPQhL/hfhlvyeoFYWHQ==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:LycoGW6ImumX6sWBWNdl7YtlFQ==,iv:58rEzzoQII15zg8VMe+zD5w4fThykHfAiUlqMNw3gZc=,tag:wJNrl/pEff+HzP4+VfVkPw==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:RVV7vUBdFFIrF7th1K5o,iv:hSl6J/KHaPda60YAtxReOvPIjyluaSxiYxlwhFYzh5M=,tag:N7pEQcYd/6SloqqZsWPt/w==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:nmenYGQzfVdpu5CNG7pN,iv:5OXr5KhsNM2XE4oYTRRhASGoxkZecMKFRZ06AbtXDU0=,tag:sVSyNMQYI+tmxO7CzWF8bg==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:iSkqZnG+9b0hMBSgYGk5l2WEdZsu7qb1DAleLOUrIi7QWLT+,iv:gYamSzsxlHtLxUOvQGBPr+X6BlWFs2Pcmz88Cc4AO6E=,tag:iK3cbKhYcF3499Z2EBPflA==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:BmjdJZIykc8csEsWwU+izTR5HXpU8bq6WePQOupvBow4jxBcK2J3EYzwO+z6oiqM9LUI+rkjnz+DW0jWDyyphauvd/jaWuydJPrHFuQfBFfa6glX465xVBd/ZFRouRltINYuG/4wAMr3ThJ+dhuZr3xj3MvhuU2DiVKhymmv3NMCP1Oud1I7zgQiLbT0/eXfjaztGx6P2cyMeLRCmtVlTAq7sjTTIiDupjNqMp94AfWiK6OTTwqkJj5rPxfKoogwdl6TZuj25ZD2R1Kn6jh4IAJbE8K+aVn2WOKNZ9zn6bQzMhyazpVxH/fdNHmacBDClTUoPCoJ7Ls=,iv:aZ2pN1vWcM8gFlzmVmSaiDFqwWcHqzW+4hTxggNj368=,tag:RDX6RPY5w5pCeCmldv18oA==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:ZsH+Us2RiIdPxPmDRclJwg8OVuoJoHM69qu1ejbI3zyCo24LZyIKEglmKLKhV4zzBveJdNQugY6HwxVF81HnAg==,iv:48X4/CYh7t2cQEEjvzahkGIeE+lDOFECJm6HlX9NmVM=,tag:r0f32hR6vBhBqw1rvSVBtA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:kyWlCf8uEJVv8Sw=,iv:fuxtEA5tYYfiyuA8wjYLI1QUQyVT9FFiGOkNw4LZzJg=,tag:na4Tpklu3HEm6M3ca3IN/Q==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:pbdcekq26ncH5dY0mJCgEg+MZgB+JuQ3k8PdDGQSchk=,iv:RqzRtTQs81Av1ezxbVeK9iOTC034vqrKAmydEAEik4Q=,tag:bfCrtf8pd4MAKduT9tj0rQ==,type:str]
  TRELLO_API_TOKEN: ENC[AES256_GCM,data:wQsm8a6ylisVD1TIFZ0MguthwNtJ7PXx9BgtXkAqvppLAcHr7oc0VOAdCAIIUiaShKqgN6RQcuT7Sd/GVL09tJ/ekH5t2Iku2Ensgw==,iv:uGhYn3JGC29KLFSRzxHnzLWobmxzAp3aikiRu75pnmk=,tag:9bceIb717OD0E/1fHTl4Uw==,type:str]
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:JkTJgoFeSSxn1DlwORQBY17KHHVYEaM/pq861kIKdgVhLJf5O7LCjgAU1kRlKd4T8C4RbSDRS4xaKtKJmW/In++pXbE26+WS3J0Cy7QtejgW4hUIyBDUB8wfpyoBRZsxkyxSY1QTOXb19MZFLmnWxqF/shqTwul+4c4nLkrwWZuIg4RkuHqADMYBNUoa+p/S92oGkIdot90Ka9heI2WZXvN+knT31kajM3gnJw==,iv:xY6dcYbUngdw3Addx0UBzKiaV3zGHcX+3NNmvIoIOQM=,tag:08kpY79Y/seEpLFWgezKVw==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:1wNjxcz0ewjTfBSKwq8NJu1CFE+tI/hhR7DUGK4JNuI=,iv:XY0VamspyWzfkAmkatAW1MEfFx9dc80f1I+kGAWX7Hc=,tag:kj5WYhgsjbTc+wBNEvC2OA==,type:str]
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:X41vQW3jJxlm5yjw8udGkKOFQxfc/lvf6K0A84YuhMun462GOFGtll3fiaa9fBQk70OxqnMrTjfhouPjVQT15GGITBb1CAIUFRixy81PfphsnLFOf5O8L90tWMv9RpXI33rtNR1e/UZerCxo,iv:MJ7HeJ9SJ9w6incl/EjqGDTt/8vbRX2Rgol9Q/moYyM=,tag:jWAt94GXurIN+GlPyHKg5A==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:3sqFm/BQ6YBiEuHbs/EpTT6f+2K8hemC9mS/NbpLYWWpjeHiGOtNTIPaCLyU1IwMV3IfT0igTAw=,iv:k3GJu1wn17WWSk8kzFoUEOnle33702GnAaR8qkgkTJU=,tag:QtCNbWdr4Xg4k/iGJ5S77A==,type:str]
  SYNOPHOTO_AUTH0_DOMAIN: ENC[AES256_GCM,data:Wtcii+Mq/eMeI0YvpmPrLDps8IZxdCCpudTrLsyF8x+0,iv:/EXgl36uM1y331NDc2doWp5RF3HHf6CBvcgXQa5zGws=,tag:MUs+aW/vMF79wJSYxXdUsw==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:Vy61w9eJgZIPgPJppU9PlWjdcuSqm7Lo+Z3qIvsuEIQ=,iv:xqly00CR1wmyEdZvfNvFgN09EvIfl9cOSDXrYAqCjkQ=,tag:aeE6kIPesKHv1MGdKLYtpA==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:QK1QdtGPbAMXNfpf502aFLhbBolIzorahBOdRuzk6g36yG5VRygsVNpLPE5RW+7plpkSzdAEWEbuJ89kdCH/LQ==,iv:3enyRjSg3xDeavYJIW8XmDzlogjZ5GQx86/ex5Vm2mk=,tag:sVcZ/jpvJSK7OMQOYT+pxQ==,type:str]
  SYNOPHOTO_ALLOWED_EMAILS: ENC[AES256_GCM,data:Eh79SnpA5Udy1E2ZtSv+8wAsPZd+bi6V/0EBq08PWKK3Qf3SAXyCZ/cwlqf2tdz3oFi9qon9Ow==,iv:BCwo1FDyxa9HguZ2q+WWceoGLJ6u2nGSzSI+DAWHpTA=,tag:XFWv1Lamfm+p0DCMzW1VDg==,type:str]
  SYNOPHOTO_FLASK_SECRET_KEY: ENC[AES256_GCM,data:Cn06Pk4D0LuJW5u3tr+gpvyIP45Bj39cqfVZpa2tq2gxajAmAlLMbHl7mzBy21/IuUhA4iana1rQqOzcCaaMUA==,iv:9/h1n340yDkqCdwihBEkS+hrB0UNSrQorIdNotLwDhU=,tag:eWxng2/+OvPmRsh8Lsz1bQ==,type:str]
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  OMNI_GPG_KEY_B64: ""
sops:
  age:
    - recipient: age1p2v4ph8cc072haxe2m6f2mlk3st6c4vrmqjy0saa32uu9rjqkgpqdpe6yf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZU53NGFZVzRJZXQzUkxa
        UUlhcCtqRVYrVFZWaWFOMUxoWnZqN1R3aHdnCkM4MGxPTHNIWDgvenhjTzc1UTBi
        MnVXNllxRFpOWTlsZ0w2UWEvUnVzODQKLS0tIDl2a21mUHV0blY4djNTVXZWZFFT
        bktHSlJQL1drZTc5OXNKR0k3cFZISzgKMSlYTrMias3UUoH4ac6bw94U3JvU0R2a
        cxREyo2EDkDHCTJW8p3vFUBXZsB4KF70tU5ISFkUdbncNRssIhyoDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T11:40:59Z"
  mac: ENC[AES256_GCM,data:0Yo3Cz4nzEz49LpNgYnZW8QRTwJ5qL/WJ9//jV8J+r1jS+QdTYQejzIh4pJ0TXTbVrJjqQlTO0nxXn44g8r6KdPbxbtLBQ81jK/g6BfLKPZHcTDzhljMsk+tzsorNVN6WhiG1VRr7XuxTraoPm17Vn0MmukcKut7/OppNQnGckg=,iv:BOP1xjLm22fZL917+OAGBcQVS2GBNoeBlIRjKTVro+Q=,tag:JNLkTE5e53/aHi46eUSgXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
