apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:QQhdEA==,iv:dJlgzFknCTKOvR+dI6U125fzjNe1iDyeIUkNpft7/Ww=,tag:F/O80TH9ziVZnUC8fAmzcQ==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:/9b+1YOXbPTEGyk=,iv:+lH345jFtgv1TcqR6dMDQ2nPTyW8RrROlAvNuaQ7zaA=,tag:YE4FogKgEFmL9yHKT0NljQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:IBVNeEFam6U=,iv:tFCcPnTrppn+kHPaJt9JkErKanQ5T+0ZTVkEr8OtV7s=,tag:CSSbpz9UDplhwg3lDc1zsw==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Dw2EBvhn47vXDeY/hCqi7lA8fv4ABFI6JK6yHWg/N64GFED2rO2Me/fyTwq10+egp7CaPu8=,iv:AzGWMX6OctG+yq/+9EILGuJr4aY9oBQC0bjyH0mWg5M=,tag:zVB4CPTP6QRjhIab13bvUw==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:LPqonq46rKY=,iv:yEnHAAN7njto0NmzmCIouGtSwPI4qHO6O0gN1+ugnV8=,tag:qrs542NEVjPDyYL0YWJVug==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:BL6CsbMJ6UA=,iv:845kC29aGmMxZJhwi+Lezc1aIqAu00bpFmxgcTxgfps=,tag:3mkrq43Ox5rHNSTryj5RlA==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:VqDeVM6NGLY=,iv:hn+Ah/4pBf2LfNw1dEAjiFZqekCBRLVbo9R1XN0OD0Y=,tag:rOX5c/9I7sBveH0ykPUZfg==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:HkFcH+j/qlta,iv:4rSAasFv3W84NI/GviwTJGT5GJhj15gnz3wczJaiTME=,tag:OSTSCQNRtw5rkyRxPwLd4g==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:rPad8LuejAddiXK3qQWHPdGyxg==,iv:raCwEAdH3+2rZ9xETmYkcDS29usILCnChFy6LNcbTvs=,tag:e9xTHlk0Gj98JWvkoKBKnA==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:Kyzw782secCAbY0a4PgZ,iv:ndPXHr8Hq1oI3xziwHy1nZwKpCq9/WxrsewQVEONcwY=,tag:6sv3cET8Ponb4ONlqkAPeQ==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:gC88qGowLopfnSOFhTga,iv:/3ycB/HUUfRiPiJRC5NXqCYXXhp9rnCyNTHrFqPkxPw=,tag:D3Ogro4cAR+1cTmRngwSNg==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:/VsxEUHhW3TOPAPcJ1CBY0zE87byZPSDt5DmuajeuQ5g8LZI,iv:e4MgdYcTeLf32MKK8AsGjTytCrxPnSU4R4toPxwTgFg=,tag:qsgGA6DtXpS4vMgsrcTjRw==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:ktZMk6/txrFpg+togA0g3rlbcROA2yCm26tjtwYvUi6fXGfD8lLyslODzo5vX2VI3BqedNIyWQqFN/Z9pRsc35FK5cWrNAr3CBqRnpwtneDR2OhPKxmz4nKxBQFH0XQ+7ryeuU+6/IPZuCLPOThdDayVgxHel0Mn+zJYkUWXyP5oiJTwxIL0/65dU92939inydSXE9eKPLw3f2dgVAbshZRJZeceWFfqjo8nseOlTtikiKLm7Ym57tWTifnsDvPnnHPQtDfpOXaQTPQBj1SrX5WIXu3Haqi65k3qdO/jlBxtfbLRNPKspGnC064zR6Mi/VeDn+R6XoI=,iv:NstPMv2ELWsxXRkagWcidXT+Raa9PRvlj958nRUUUYQ=,tag:Cw/1/+6tfLYiT8Y3OAgeWQ==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:/z4jxom9wAqsAJpFQDykK+R4Dwrwyg8xZpPOdK88O9xlUA+tdlkIeaykmtnNZO7m3j9185uF9AQoJ+yuox0LkA==,iv:lMrCAP9NnbZE6zXBfjvOmSitGtqWPRNfIiJ9FQmq+2g=,tag:bAxYKCVzOPq9TvJEnPplvg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:65zljh4i3JhPLPs=,iv:38QUzB69A5a5SPw5dz8Wyv7pTpgupmQSU1og9vGhLFE=,tag:BOxc6EVMjuPDz6RaOHx79Q==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:/Qtjh62NlLN3CJOqSLfofLwKYJ38Gv2UxWSpzdlmLeY=,iv:JPF3KP18Qyb1Ql7UAacsJp+hIQ+IOouI4v2iG/q9CB4=,tag:2YVaLUl1mD/6ljZ+yB7iWg==,type:str]
  TRELLO_API_TOKEN: ENC[AES256_GCM,data:5R19/bleFXlGNr28qqZvG57Bn0ONuvDSxMYal3bBgQNWSd8tQ66DIYb3jit8iF0PxnLmJYN4V1IhjU9wRZfzR2GOtF9tc70v+4Iq+Q==,iv:9NS/1uO74sPBZXLCYCS997UYW2cJRAYeIt31OOxhLBA=,tag:mLl5aq5Pp1yt4nVe8p03qA==,type:str]
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:Y6nq2ky9dK0wX1UUVQuBihQOpRUER3h9M1UnuBGttAsLm2r2NtDJtXJgz/r5FidU7y1FTE4QO2Ry4VXRwS+V7YQlwStOX9N2wcUGRtG43p6tf7uE978r81JoqM+BdGAX6m3YHlOoT7YgL+D5+z4FJ81PT1n6zdzdI7H5tmIwEgfd4JZWjgr+66x03ggHkQMJ5Fi7RhFFCFw9stz+P3IaWLdNcrnHTeMQUPjkIw==,iv:rixGCnZVfn0JhgcvUOl0m+ywxsH/ijZtXOcZlIszDkw=,tag:QhhaqrSWunkbLRrhlOqziQ==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:dHWAhoEPyz5J20HT81lUWK9+wgUpADULdFXl/9OCbeE=,iv:GDkXsZ/2Fv0gZhBxpII0K7027+32mqGvrzSG2orCWl4=,tag:zBqWLyO3IThPlqZYRKTFWA==,type:str]
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:folbx4GcTPtsnEe/CioxhLzdeiMYXw3JE8smk7uPGcRlLHOI3fHGVnfLRf182MYRRzHUg+OxVSGTRH80k/Yr04IRpfDPUG0LLm97cKmStCJ/iNhYG9ipa/uELpSliTuPKgu5ntYRsx1P6B9p,iv:AFvoZxtWE1kPT3kiXl2bIBJ1DUcqdfRjk3FcKhyxx4E=,tag:OdKLp1Gl/gabvShNxqzgeQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:xo5U9Y7u2eZ3uPSdMFvVxusb6kcy1VYUxyTJ0KWiZy9+L0JEGKP2kxc2I6O7Tkhn3KE1wsiuWGk=,iv:ghttjRKvYkUksT6gFNxydgnJC6FwcRYhQKynqAP2kdU=,tag:BNBuhV2d5dO3oHmP7UhO+g==,type:str]
  SYNOPHOTO_AUTH0_DOMAIN: ENC[AES256_GCM,data:bRiH4WTVoskuXFbgxyDHKhuF8QsQFRDNwxQkMAoeawx8,iv:Ip2IQYQ2KGZLwKtdSibXzJdbbRgJdqIFtCvQP2+ySMs=,tag:7q184yaGGYrC+K9uOBellQ==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:6pVtOlvgmn6byKON3iAEvMwVzH4y08Lw7tiwQ0rzAx8=,iv:AzeL/ZnP8GG7Btdp+jBol3UwhDW6Ijg1QsNwnTcZA8M=,tag:dzc0h5hhMYyUucwHmJCtkA==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:ed8bUG6+JB6G2mAyb+/IRnp7QVKFkRRoNIz1xB/0pYE5w9sR3U8yxOvejjVqRL6SaeGPO1TP0NshNtM4VZS2nw==,iv:6nHHGKD/+Sv9Vs9UOmxfvf1EkmffuDaxzoJYz0QduOM=,tag:wj/9skltuxDrhmUCo45+mw==,type:str]
  SYNOPHOTO_ALLOWED_EMAILS: ENC[AES256_GCM,data:iFf7PkHzsPYnhbVT1h1l4URPGsP8YvirHqkM8+sk1zQ8z4+ytuwUIclntUSVdAaRQ4zJH6ncCA==,iv:szXgFIRDG7ynLOcosEoIHZSPM9ClTsJ8xw3xR7o0ca0=,tag:mJx/Zew++OG2KmhTp9Ks9Q==,type:str]
  SYNOPHOTO_FLASK_SECRET_KEY: ENC[AES256_GCM,data:zlTZR/CLCAanfkB7T2WMRkXtEBoOY/0BIfzWsZb8qX8odgpd1M/zneM8qxT8Dfpht6V4E1VmFHGehd2viN/3sw==,iv:pC2ncAy/S6wZumA6T0+5wQNavsC8D4isMiNCSpJntUE=,tag:kvSecU/mOUVz0KVdQhWUrA==,type:str]
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  OMNI_GPG_KEY_B64: ""
sops:
  age:
    - recipient: age1p2v4ph8cc072haxe2m6f2mlk3st6c4vrmqjy0saa32uu9rjqkgpqdpe6yf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZzFvenFOVW5YU1NjQ2VX
        NUFLcjdDZnprcUNQSHpDWWRTK3Z0MEptbm5zClVVNzBlN0t0ZHQxNlJFV0pKVFRT
        SEVocGd5YzJzaEQvMmhVZWFzb3BoMGcKLS0tIEhVNFYxdUhWUXdMUDJJdGpyR205
        aUNTZWJvSmluem5laXRUSjQ2aklCdDAKUnuosp1nJR6gtgXvl1FaU1KzDF1mODza
        uWhPv7WR6vPaPBVLyrs4hvxiLwUT19KCLxY/b6ZLUzg9apGP4UejDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-15T13:47:06Z"
  mac: ENC[AES256_GCM,data:/C5EI3ghvNI3OCZY727Fu2bx9cVKSC4EPigt77jCS5wiyKfHyyYJ/6OvVTJLrBu0Suw0xMbBQr1+7vmJA1vK3ZcEpyKPU+RzDS18REyyoMldlazo3sYa3Qdw3SCGSzQicupAyST/kJFs2GCOFoNWUS04zJPUu/guM77Wcv8k34I=,iv:SKFzy1uvyRqvqoRXXvxmmN7bdB+B+ag6YaMR5/BW3UA=,tag:lwpML8DrcrFJXbSzPaPucw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
